### ISSUE TITLE
slacker-cli broken 

### ISSUE THREAD

**Issue by billygout** [juanpabloaj/slacker-cli#33]
As of commit
https://github.com/os/slacker/commit/2ce958e3816dde6e7a0056ac103063142963e651, slacker-cli seems to be broken, as shown here:
```
(env) $ pip list | grep slacker
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
slacker         0.13.0  
slacker-cli     0.4.0   
(env) $ echo hello | slacker
Traceback (most recent call last):
  File "/env/bin/slacker", line 6, in <module>
    from slacker_cli import main
  File "/env/local/lib/python2.7/site-packages/slacker_cli/__init__.py", line 8, in <module>
    from slacker.utils import get_item_id_by_name
ImportError: No module named utils
(env) $
```

**Comment by hugovk** [comment]
This is because:

* The most recent Slacker release v0.13.0 renamed its `utils` module to `utilities` https://github.com/os/slacker/releases/tag/v0.13.0

* The version (0.4.0) of slacker-cli on PyPI requires `slacker>=0.7.3` (in requirements.txt)

* The unreleased master of slacker-cli pins to `slacker==0.9.65` so the tests pass

Please see PR https://github.com/juanpabloaj/slacker-cli/pull/35 for a fix.

**Comment by juanpabloaj** [comment]
@billygout Thanks for your feedback. I uploaded the version 0.4.1 with the hugovk's PR #35. 

@hugovk thanks again for your PR.

**Comment by hugovk** [comment]
You're welcome! Thanks for the new release, and thanks @billygout for the report!
